name: "<serviceName>"
replicaCount: 1

images:
  PullSecrets: 
    name: <ACRreg>
  repository: <your-project-acr-name>.azurecr.io/values-test
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

config:
  configmaps: [<your-configmap>]


ingress:
  enabled: true
  hosts:
  - host: <your-dns-name>.branch-yesodot.org
    paths:
      - path: /<something>
        service: service
        port: "3000"
